version: "3.9"
services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DATABASE_URL=postgresql+psycopg2://user:pass@db:5432/appdb"
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "35432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
